// components/sections/registry.ts
import type { ComponentRegistryEntry } from '@/types/section-system';
import { HeroSplitImageLeft } from './HeroSplitImageLeft';
import { HeroGradientSpotlight } from './HeroGradientSpotlight';
import { HeroVideoBackground } from './HeroVideoBackground';
import { HeroParallaxScroll } from './HeroParallaxScroll';
import { HeroAnimatedText } from './HeroAnimatedText';
import { FeaturesCards3Up } from './FeaturesCards3Up';
import { FeaturesIconGrid } from './FeaturesIconGrid';
import { FeaturesTimeline } from './FeaturesTimeline';
import { CTAGradientSlab } from './CTAGradientSlab';
import { TestimonialsGrid2x2 } from './TestimonialsGrid2x2';
import { FooterMega } from './FooterMega';
import { NavBasic } from './NavBasic';
import { PricingTable3Tier } from './PricingTable3Tier';
import { PricingTiered } from './PricingTiered';
import { PricingComparison } from './PricingComparison';
import { ContactFormBasic } from './ContactFormBasic';
import { GalleryMasonry } from './GalleryMasonry';
import { BlogListStandard } from './BlogListStandard';
import { AboutTeamGrid } from './AboutTeamGrid';
import { AboutStoryTimeline } from './AboutStoryTimeline';
import { AboutMissionValues } from './AboutMissionValues';
import { FAQAccordion } from './FAQAccordion';
import { FAQGrid } from './FAQGrid';
import { ContactSplitMap } from './ContactSplitMap';
import { ContactMultiChannel } from './ContactMultiChannel';
import { GalleryGrid } from './GalleryGrid';
import { GalleryCarousel } from './GalleryCarousel';
import { BlogCardGrid } from './BlogCardGrid';
import { HeroMinimal } from './HeroMinimal';
import { HeroFullBleed } from './HeroFullBleed';
import { HeroCentered } from './HeroCentered';
import { HeroWithForm } from './HeroWithForm';
import { HeroCardOverlay } from './HeroCardOverlay';
import { FeaturesIconList } from './FeaturesIconList';
import { FeaturesComparison } from './FeaturesComparison';
import { FeaturesBentoGrid } from './FeaturesBentoGrid';
import { FeaturesAccordion } from './FeaturesAccordion';
import { FeaturesSplitList } from './FeaturesSplitList';

export const componentRegistry: Record<string, ComponentRegistryEntry> = {
  'hero-gradient-spotlight': {
    component: HeroGradientSpotlight as any,
    meta: {
      kind: 'hero',
      variant: 'gradient-spotlight',
      name: 'Hero • Gradient Spotlight',
      description: 'Animated gradient background with spotlight effects.',
      contentSlots: [
        { key: 'headline', type: 'text', required: true, maxLength: 100 },
        { key: 'subheadline', type: 'text', required: false, maxLength: 200 },
        { key: 'primaryCta', type: 'action', required: true },
        { key: 'secondaryCta', type: 'action', required: false },
        { key: 'stats', type: 'stat[]', required: false, maxLength: 3 },
      ],
      hardConstraints: ['h1_once_per_page', 'mobile_first'],
      softConstraints: ['prefer_high_contrast', 'limit_animations'],
      a11yChecklist: ['contrast_aa', 'focus_visible', 'keyboard_navigable', 'reduced_motion_safe'],
      bestFor: ['saas', 'product', 'landing', 'agency'],
      avoidFor: ['blog', 'documentation'],
      estimatedSize: 'xl',
      hasAnimations: true,
      requiresJs: false,
    },
  },
  'hero-video-background': {
    component: HeroVideoBackground as any,
    meta: {
      kind: 'hero',
      variant: 'video-background',
      name: 'Hero • Video Background',
      description: 'Full-screen video background with overlay text.',
      contentSlots: [
        { key: 'headline', type: 'text', required: true, maxLength: 100 },
        { key: 'subheadline', type: 'text', required: false, maxLength: 200 },
        { key: 'videoUrl', type: 'text', required: false },
        { key: 'primaryCta', type: 'action', required: true },
      ],
      hardConstraints: ['h1_once_per_page', 'mobile_first'],
      softConstraints: ['limit_animations', 'avoid_adjacent_heavy_imagery'],
      a11yChecklist: ['contrast_aa', 'focus_visible', 'keyboard_navigable', 'reduced_motion_safe'],
      bestFor: ['saas', 'product', 'agency', 'creative'],
      avoidFor: ['blog', 'documentation'],
      estimatedSize: 'xl',
      hasAnimations: true,
      requiresJs: false,
    },
  },
  'hero-parallax-scroll': {
    component: HeroParallaxScroll as any,
    meta: {
      kind: 'hero',
      variant: 'parallax-scroll',
      name: 'Hero • Parallax Scroll',
      description: 'Depth effect with parallax scrolling layers.',
      contentSlots: [
        { key: 'headline', type: 'text', required: true, maxLength: 100 },
        { key: 'subheadline', type: 'text', required: false, maxLength: 200 },
      ],
      hardConstraints: ['h1_once_per_page', 'mobile_first'],
      softConstraints: ['limit_animations', 'avoid_dense_text_mobile'],
      a11yChecklist: ['contrast_aa', 'focus_visible', 'reduced_motion_safe'],
      bestFor: ['creative', 'portfolio', 'agency'],
      avoidFor: ['documentation'],
      estimatedSize: 'lg',
      hasAnimations: true,
      requiresJs: true,
    },
  },
  'hero-animated-text': {
    component: HeroAnimatedText as any,
    meta: {
      kind: 'hero',
      variant: 'animated-text',
      name: 'Hero • Animated Text',
      description: 'Rotating text animation for dynamic messaging.',
      contentSlots: [
        { key: 'animatedWords', type: 'text[]', required: true, minLength: 2, maxLength: 6 },
        { key: 'subheadline', type: 'text', required: false, maxLength: 200 },
      ],
      hardConstraints: ['h1_once_per_page', 'mobile_first'],
      softConstraints: ['limit_animations'],
      a11yChecklist: ['contrast_aa', 'focus_visible', 'screen_reader_friendly'],
      bestFor: ['creative', 'agency', 'startup'],
      avoidFor: ['corporate', 'documentation'],
      estimatedSize: 'md',
      hasAnimations: true,
      requiresJs: true,
    },
  },
  'hero-split-image-left': {
    component: HeroSplitImageLeft as any,
    meta: {
      kind: 'hero',
      variant: 'split-image-left',
      name: 'Hero • Split Image Left',
      description: 'Split layout with content on right, image on left.',
      contentSlots: [
        { key: 'headline', type: 'text', required: true, maxLength: 100 },
        { key: 'subheadline', type: 'text', required: false, maxLength: 200 },
        { key: 'bullets', type: 'text[]', required: false, maxLength: 6 },
      ],
      hardConstraints: ['h1_once_per_page', 'img_alt_required', 'mobile_first'],
      softConstraints: ['avoid_dense_text_mobile', 'optimize_for_thumb_reach'],
      a11yChecklist: ['contrast_aa', 'focus_visible', 'keyboard_navigable'],
      bestFor: ['saas', 'agency', 'product'],
      avoidFor: ['blog', 'news'],
      estimatedSize: 'lg',
      hasAnimations: false,
      requiresJs: false,
    },
  },
  'hero-minimal': {
    component: HeroMinimal as any,
    meta: {
      kind: 'hero',
      variant: 'minimal',
      name: 'Hero • Minimal',
      description: 'Clean, centered hero with minimal design.',
      contentSlots: [
        { key: 'headline', type: 'text', required: true, maxLength: 100 },
        { key: 'subheadline', type: 'text', required: false, maxLength: 200 },
        { key: 'primaryCta', type: 'action', required: false },
        { key: 'secondaryCta', type: 'action', required: false },
      ],
      hardConstraints: ['h1_once_per_page', 'mobile_first'],
      softConstraints: ['prefer_high_contrast', 'optimize_for_thumb_reach'],
      a11yChecklist: ['contrast_aa', 'focus_visible', 'keyboard_navigable'],
      bestFor: ['saas', 'product', 'agency', 'portfolio'],
      avoidFor: [],
      estimatedSize: 'md',
      hasAnimations: false,
      requiresJs: false,
    },
  },
  'hero-full-bleed': {
    component: HeroFullBleed as any,
    meta: {
      kind: 'hero',
      variant: 'full-bleed',
      name: 'Hero • Full Bleed',
      description: 'Full-screen hero with background image and overlay.',
      contentSlots: [
        { key: 'headline', type: 'text', required: true, maxLength: 100 },
        { key: 'subheadline', type: 'text', required: false, maxLength: 200 },
        { key: 'eyebrow', type: 'text', required: false, maxLength: 50 },
        { key: 'primaryCta', type: 'action', required: false },
        { key: 'secondaryCta', type: 'action', required: false },
        { key: 'backgroundImage', type: 'text', required: false },
      ],
      hardConstraints: ['h1_once_per_page', 'mobile_first', 'img_alt_required'],
      softConstraints: ['limit_animations', 'avoid_adjacent_heavy_imagery'],
      a11yChecklist: ['contrast_aa', 'focus_visible', 'keyboard_navigable', 'reduced_motion_safe'],
      bestFor: ['agency', 'creative', 'portfolio', 'product'],
      avoidFor: ['documentation', 'blog'],
      estimatedSize: 'xl',
      hasAnimations: false,
      requiresJs: false,
    },
  },
  'hero-centered': {
    component: HeroCentered as any,
    meta: {
      kind: 'hero',
      variant: 'minimal',
      name: 'Hero • Centered',
      description: 'Centered hero with badges and trust indicators.',
      contentSlots: [
        { key: 'badge', type: 'text', required: false, maxLength: 30 },
        { key: 'headline', type: 'text', required: true, maxLength: 100 },
        { key: 'subheadline', type: 'text', required: false, maxLength: 200 },
        { key: 'primaryCta', type: 'action', required: false },
        { key: 'secondaryCta', type: 'action', required: false },
        { key: 'trustIndicators', type: 'text[]', required: false, maxLength: 4 },
      ],
      hardConstraints: ['h1_once_per_page', 'mobile_first'],
      softConstraints: ['prefer_high_contrast', 'optimize_for_thumb_reach'],
      a11yChecklist: ['contrast_aa', 'focus_visible', 'keyboard_navigable'],
      bestFor: ['saas', 'product', 'landing'],
      avoidFor: ['blog'],
      estimatedSize: 'lg',
      hasAnimations: false,
      requiresJs: false,
    },
  },
  'hero-with-form': {
    component: HeroWithForm as any,
    meta: {
      kind: 'hero',
      variant: 'with-form',
      name: 'Hero • With Form',
      description: 'Split hero with signup form on the right.',
      contentSlots: [
        { key: 'eyebrow', type: 'text', required: false, maxLength: 30 },
        { key: 'headline', type: 'text', required: true, maxLength: 100 },
        { key: 'subheadline', type: 'text', required: false, maxLength: 200 },
        { key: 'features', type: 'text[]', required: false, maxLength: 5 },
        { key: 'formTitle', type: 'text', required: false, maxLength: 50 },
        { key: 'formSubtitle', type: 'text', required: false, maxLength: 100 },
        { key: 'formCta', type: 'text', required: false, maxLength: 30 },
      ],
      hardConstraints: ['h1_once_per_page', 'mobile_first', 'form_label_required'],
      softConstraints: ['optimize_for_thumb_reach', 'avoid_dense_text_mobile'],
      a11yChecklist: ['contrast_aa', 'focus_visible', 'keyboard_navigable', 'screen_reader_friendly'],
      bestFor: ['saas', 'product', 'landing'],
      avoidFor: ['blog', 'documentation'],
      estimatedSize: 'xl',
      hasAnimations: false,
      requiresJs: true,
    },
  },
  'hero-card-overlay': {
    component: HeroCardOverlay as any,
    meta: {
      kind: 'hero',
      variant: 'card-over-image',
      name: 'Hero • Card Overlay',
      description: 'Hero with overlapping card or image.',
      contentSlots: [
        { key: 'badge', type: 'text', required: false, maxLength: 30 },
        { key: 'headline', type: 'text', required: true, maxLength: 100 },
        { key: 'subheadline', type: 'text', required: false, maxLength: 200 },
        { key: 'primaryCta', type: 'action', required: false },
        { key: 'secondaryCta', type: 'action', required: false },
        { key: 'stats', type: 'stat[]', required: false, maxLength: 3 },
        { key: 'imageUrl', type: 'text', required: false },
        { key: 'cardTitle', type: 'text', required: false, maxLength: 50 },
        { key: 'cardFeatures', type: 'text[]', required: false, maxLength: 5 },
        { key: 'cardOverlay', type: 'text', required: false, maxLength: 100 },
      ],
      hardConstraints: ['h1_once_per_page', 'mobile_first'],
      softConstraints: ['avoid_dense_text_mobile', 'optimize_for_thumb_reach'],
      a11yChecklist: ['contrast_aa', 'focus_visible', 'keyboard_navigable'],
      bestFor: ['saas', 'product', 'agency'],
      avoidFor: ['blog', 'documentation'],
      estimatedSize: 'xl',
      hasAnimations: false,
      requiresJs: false,
    },
  },
  'features-cards-3up': {
    component: FeaturesCards3Up as any,
    meta: {
      kind: 'features',
      variant: 'cards-3up',
      name: 'Features • Cards (3-up)',
      description: 'Three feature cards in a responsive grid.',
      contentSlots: [
        { key: 'headline', type: 'text', required: false, maxLength: 100 },
        { key: 'subheadline', type: 'text', required: false, maxLength: 200 },
        // We expect 'features' (string[]). The beam search maps items->features if needed.
        { key: 'features', type: 'text[]', required: true, minLength: 3, maxLength: 6 },
      ],
      hardConstraints: ['mobile_first'],
      softConstraints: ['avoid_dense_text_mobile'],
      a11yChecklist: ['contrast_aa', 'keyboard_navigable'],
      bestFor: ['saas', 'product', 'service'],
      avoidFor: [],
      estimatedSize: 'md',
      hasAnimations: false,
      requiresJs: false,
    },
  },
  'features-icon-grid': {
    component: FeaturesIconGrid as any,
    meta: {
      kind: 'features',
      variant: 'icon-grid',
      name: 'Features • Icon Grid',
      description: 'Grid layout with icons and descriptions.',
      contentSlots: [
        { key: 'headline', type: 'text', required: false, maxLength: 100 },
        { key: 'subheadline', type: 'text', required: false, maxLength: 200 },
        { key: 'features', type: 'feature[]', required: true, minLength: 4, maxLength: 8 },
      ],
      hardConstraints: ['mobile_first'],
      softConstraints: ['optimize_for_thumb_reach'],
      a11yChecklist: ['contrast_aa', 'keyboard_navigable'],
      bestFor: ['saas', 'product', 'service'],
      avoidFor: [],
      estimatedSize: 'md',
      hasAnimations: false,
      requiresJs: false,
    },
  },
  'features-timeline': {
    component: FeaturesTimeline as any,
    meta: {
      kind: 'features',
      variant: 'timeline',
      name: 'Features • Timeline',
      description: 'Chronological timeline with milestones.',
      contentSlots: [
        { key: 'headline', type: 'text', required: false, maxLength: 100 },
        { key: 'subheadline', type: 'text', required: false, maxLength: 200 },
        { key: 'timeline', type: 'milestone[]', required: true, minLength: 3, maxLength: 8 },
      ],
      hardConstraints: ['mobile_first'],
      softConstraints: ['avoid_dense_text_mobile'],
      a11yChecklist: ['contrast_aa', 'keyboard_navigable', 'screen_reader_friendly'],
      bestFor: ['about', 'company', 'product'],
      avoidFor: [],
      estimatedSize: 'lg',
      hasAnimations: false,
      requiresJs: false,
    },
  },
  'features-icon-list': {
    component: FeaturesIconList as any,
    meta: {
      kind: 'features',
      variant: 'icon-list',
      name: 'Features • Icon List',
      description: 'Grid of features with icons and descriptions.',
      contentSlots: [
        { key: 'eyebrow', type: 'text', required: false, maxLength: 30 },
        { key: 'headline', type: 'text', required: true, maxLength: 100 },
        { key: 'subheadline', type: 'text', required: false, maxLength: 200 },
        { key: 'features', type: 'feature[]', required: true, minLength: 3, maxLength: 9 },
        { key: 'cta', type: 'action', required: false },
      ],
      hardConstraints: ['mobile_first'],
      softConstraints: ['avoid_dense_text_mobile', 'optimize_for_thumb_reach'],
      a11yChecklist: ['contrast_aa', 'keyboard_navigable', 'screen_reader_friendly'],
      bestFor: ['saas', 'product', 'agency', 'landing'],
      avoidFor: [],
      estimatedSize: 'lg',
      hasAnimations: false,
      requiresJs: false,
    },
  },
  'features-comparison': {
    component: FeaturesComparison as any,
    meta: {
      kind: 'features',
      variant: 'comparison',
      name: 'Features • Comparison Table',
      description: 'Pricing/feature comparison table with plans.',
      contentSlots: [
        { key: 'headline', type: 'text', required: true, maxLength: 100 },
        { key: 'subheadline', type: 'text', required: false, maxLength: 200 },
        { key: 'plans', type: 'plan[]', required: true, minLength: 2, maxLength: 4 },
      ],
      hardConstraints: ['mobile_first'],
      softConstraints: ['avoid_dense_text_mobile'],
      a11yChecklist: ['contrast_aa', 'keyboard_navigable', 'screen_reader_friendly'],
      bestFor: ['saas', 'product', 'pricing'],
      avoidFor: ['blog', 'portfolio'],
      estimatedSize: 'xl',
      hasAnimations: false,
      requiresJs: false,
    },
  },
  'features-bento-grid': {
    component: FeaturesBentoGrid as any,
    meta: {
      kind: 'features',
      variant: 'bento-grid',
      name: 'Features • Bento Grid',
      description: 'Modern bento box layout with mixed card sizes.',
      contentSlots: [
        { key: 'headline', type: 'text', required: true, maxLength: 100 },
        { key: 'subheadline', type: 'text', required: false, maxLength: 200 },
        { key: 'features', type: 'feature[]', required: true, minLength: 4, maxLength: 8 },
      ],
      hardConstraints: ['mobile_first'],
      softConstraints: ['avoid_dense_text_mobile'],
      a11yChecklist: ['contrast_aa', 'keyboard_navigable', 'screen_reader_friendly'],
      bestFor: ['saas', 'product', 'creative', 'modern'],
      avoidFor: ['corporate', 'traditional'],
      estimatedSize: 'xl',
      hasAnimations: true,
      requiresJs: false,
    },
  },
  'features-accordion': {
    component: FeaturesAccordion as any,
    meta: {
      kind: 'features',
      variant: 'accordion',
      name: 'Features • Accordion',
      description: 'Expandable accordion-style features list.',
      contentSlots: [
        { key: 'headline', type: 'text', required: true, maxLength: 100 },
        { key: 'subheadline', type: 'text', required: false, maxLength: 200 },
        { key: 'features', type: 'feature[]', required: true, minLength: 3, maxLength: 8 },
      ],
      hardConstraints: ['mobile_first'],
      softConstraints: ['avoid_dense_text_mobile'],
      a11yChecklist: ['contrast_aa', 'keyboard_navigable', 'screen_reader_friendly'],
      bestFor: ['saas', 'product', 'faq', 'documentation'],
      avoidFor: [],
      estimatedSize: 'lg',
      hasAnimations: true,
      requiresJs: true,
    },
  },
  'features-split-list': {
    component: FeaturesSplitList as any,
    meta: {
      kind: 'features',
      variant: 'split-list',
      name: 'Features • Split List',
      description: 'Split layout with features list and content side.',
      contentSlots: [
        { key: 'headline', type: 'text', required: true, maxLength: 100 },
        { key: 'subheadline', type: 'text', required: false, maxLength: 200 },
        { key: 'features', type: 'feature[]', required: true, minLength: 3, maxLength: 6 },
        { key: 'imageUrl', type: 'text', required: false },
        { key: 'stats', type: 'stat[]', required: false, maxLength: 4 },
        { key: 'cta', type: 'action', required: false },
      ],
      hardConstraints: ['mobile_first', 'img_alt_required'],
      softConstraints: ['avoid_dense_text_mobile', 'optimize_for_thumb_reach'],
      a11yChecklist: ['contrast_aa', 'keyboard_navigable', 'screen_reader_friendly'],
      bestFor: ['saas', 'product', 'agency', 'landing'],
      avoidFor: [],
      estimatedSize: 'xl',
      hasAnimations: false,
      requiresJs: false,
    },
  },
  'cta-gradient-slab': {
    component: CTAGradientSlab as any,
    meta: {
      kind: 'cta',
      variant: 'gradient-slab',
      name: 'CTA • Gradient Slab',
      description: 'Full-width gradient background with centered CTA.',
      contentSlots: [
        { key: 'headline', type: 'text', required: true, maxLength: 100 },
        { key: 'description', type: 'text', required: false, maxLength: 240 },
        { key: 'disclaimer', type: 'text', required: false, maxLength: 120 },
      ],
      hardConstraints: ['cta_required', 'mobile_first'],
      softConstraints: ['prefer_high_contrast'],
      a11yChecklist: ['contrast_aa', 'focus_visible', 'keyboard_navigable'],
      bestFor: ['saas', 'product', 'landing'],
      avoidFor: ['documentation'],
      estimatedSize: 'sm',
      hasAnimations: false,
      requiresJs: false,
    },
  },

  'testimonials-grid-2x2': {
    component: TestimonialsGrid2x2 as any,
    meta: {
      kind: 'testimonials',
      variant: 'grid-2x2',
      name: 'Testimonials • Grid 2×2',
      description: 'Four quotes in a 2×2 responsive grid with avatars and star ratings.',
      contentSlots: [
        { key: 'headline', type: 'text', required: false, maxLength: 100 },
        { key: 'subheadline', type: 'text', required: false, maxLength: 200 },
        { key: 'quotes', type: 'quote', required: true },
      ],
      hardConstraints: ['mobile_first'],
      softConstraints: ['avoid_dense_text_mobile'],
      a11yChecklist: ['contrast_aa', 'keyboard_navigable', 'screen_reader_friendly'],
      bestFor: ['saas', 'product', 'agency', 'landing'],
      avoidFor: ['documentation'],
      estimatedSize: 'md',
      hasAnimations: false,
      requiresJs: false,
    },
  },
  
  'footer-mega': {
    component: FooterMega as any,
    meta: {
      kind: 'footer',
      variant: 'mega',
      name: 'Footer • Mega',
      description: 'Five-column mega footer with headings and link lists.',
      contentSlots: [
        { key: 'columns', type: 'text[]', required: true },
        { key: 'legal', type: 'text', required: false, maxLength: 200 },
      ],
      hardConstraints: ['mobile_first'],
      softConstraints: ['avoid_dense_text_mobile'],
      a11yChecklist: ['contrast_aa', 'keyboard_navigable', 'screen_reader_friendly'],
      bestFor: ['saas','agency','product','landing'],
      avoidFor: [],
      estimatedSize: 'sm',
      hasAnimations: false,
      requiresJs: false,
    },
  },
  'navigation-basic': {
    component: NavBasic as any,
    meta: {
      kind: 'navigation',
      variant: 'basic',
      name: 'Navigation • Basic',
      description: 'A simple navigation bar with a logo and links.',
      contentSlots: [],
      hardConstraints: [],
      softConstraints: [],
      a11yChecklist: [],
      bestFor: [],
      avoidFor: [],
      estimatedSize: 'sm',
      hasAnimations: false,
      requiresJs: false,
    },
  },
  'pricing-table-3-tier': {
    component: PricingTable3Tier as any,
    meta: {
      kind: 'pricing',
      variant: 'table-3-tier',
      name: 'Pricing • 3-Tier Table',
      description: 'A pricing table with three tiers.',
      contentSlots: [],
      hardConstraints: [],
      softConstraints: [],
      a11yChecklist: [],
      bestFor: [],
      avoidFor: [],
      estimatedSize: 'md',
      hasAnimations: false,
      requiresJs: false,
    },
  },
  'contact-form-basic': {
    component: ContactFormBasic as any,
    meta: {
      kind: 'contact',
      variant: 'form-basic',
      name: 'Contact • Basic Form',
      description: 'A simple contact form.',
      contentSlots: [],
      hardConstraints: [],
      softConstraints: [],
      a11yChecklist: [],
      bestFor: [],
      avoidFor: [],
      estimatedSize: 'md',
      hasAnimations: false,
      requiresJs: false,
    },
  },
  'gallery-masonry': {
    component: GalleryMasonry as any,
    meta: {
      kind: 'gallery',
      variant: 'masonry',
      name: 'Gallery • Masonry',
      description: 'A masonry-style image gallery.',
      contentSlots: [],
      hardConstraints: [],
      softConstraints: [],
      a11yChecklist: [],
      bestFor: [],
      avoidFor: [],
      estimatedSize: 'lg',
      hasAnimations: false,
      requiresJs: false,
    },
  },
  'blog-list-standard': {
    component: BlogListStandard as any,
    meta: {
      kind: 'blog',
      variant: 'list-standard',
      name: 'Blog • Standard List',
      description: 'A standard list of blog posts.',
      contentSlots: [],
      hardConstraints: [],
      softConstraints: [],
      a11yChecklist: [],
      bestFor: [],
      avoidFor: [],
      estimatedSize: 'lg',
      hasAnimations: false,
      requiresJs: false,
    },
  },
  'about-team-grid': {
    component: AboutTeamGrid as any,
    meta: {
      kind: 'about',
      variant: 'team-grid',
      name: 'About • Team Grid',
      description: 'Grid layout showcasing team members with photos and bios.',
      contentSlots: [
        { key: 'headline', type: 'text', required: true, maxLength: 100 },
        { key: 'subheadline', type: 'text', required: false, maxLength: 200 },
        { key: 'team', type: 'member[]', required: false },
      ],
      hardConstraints: ['mobile_first'],
      softConstraints: ['avoid_adjacent_heavy_imagery'],
      a11yChecklist: ['contrast_aa', 'keyboard_navigable'],
      bestFor: ['corporate', 'agency', 'startup'],
      avoidFor: ['product', 'documentation'],
      estimatedSize: 'lg',
      hasAnimations: false,
      requiresJs: false,
    },
  },
  'about-story-timeline': {
    component: AboutStoryTimeline as any,
    meta: {
      kind: 'about',
      variant: 'story-timeline',
      name: 'About • Story Timeline',
      description: 'Timeline visualization of company history and milestones.',
      contentSlots: [
        { key: 'headline', type: 'text', required: true, maxLength: 100 },
        { key: 'subheadline', type: 'text', required: false, maxLength: 200 },
        { key: 'story', type: 'milestone[]', required: false },
      ],
      hardConstraints: ['mobile_first'],
      softConstraints: ['avoid_dense_text_mobile'],
      a11yChecklist: ['contrast_aa', 'keyboard_navigable', 'screen_reader_friendly'],
      bestFor: ['corporate', 'startup', 'non-profit'],
      avoidFor: ['product', 'documentation'],
      estimatedSize: 'md',
      hasAnimations: false,
      requiresJs: false,
    },
  },
  'about-mission-values': {
    component: AboutMissionValues as any,
    meta: {
      kind: 'about',
      variant: 'mission-values',
      name: 'About • Mission & Values',
      description: 'Company mission statement with core values grid.',
      contentSlots: [
        { key: 'headline', type: 'text', required: true, maxLength: 100 },
        { key: 'mission', type: 'text', required: true, maxLength: 500 },
        { key: 'values', type: 'value[]', required: false },
      ],
      hardConstraints: ['mobile_first'],
      softConstraints: ['optimize_for_thumb_reach'],
      a11yChecklist: ['contrast_aa', 'keyboard_navigable'],
      bestFor: ['corporate', 'non-profit', 'agency'],
      avoidFor: ['product', 'documentation'],
      estimatedSize: 'md',
      hasAnimations: false,
      requiresJs: false,
    },
  },
  'pricing-tiered': {
    component: PricingTiered as any,
    meta: {
      kind: 'pricing',
      variant: 'tiered',
      name: 'Pricing • Tiered Plans',
      description: 'Classic tiered pricing with highlighted recommended plan.',
      contentSlots: [
        { key: 'headline', type: 'text', required: true, maxLength: 100 },
        { key: 'subheadline', type: 'text', required: false, maxLength: 200 },
        { key: 'plans', type: 'plan[]', required: true },
      ],
      hardConstraints: ['mobile_first'],
      softConstraints: ['prefer_high_contrast'],
      a11yChecklist: ['contrast_aa', 'keyboard_navigable', 'focus_visible'],
      bestFor: ['saas', 'product', 'service'],
      avoidFor: ['blog', 'documentation'],
      estimatedSize: 'lg',
      hasAnimations: false,
      requiresJs: false,
    },
  },
  'pricing-comparison': {
    component: PricingComparison as any,
    meta: {
      kind: 'pricing',
      variant: 'comparison',
      name: 'Pricing • Comparison Table',
      description: 'Feature comparison table across pricing tiers.',
      contentSlots: [
        { key: 'headline', type: 'text', required: true, maxLength: 100 },
        { key: 'subheadline', type: 'text', required: false, maxLength: 200 },
        { key: 'comparison', type: 'comparison', required: true },
      ],
      hardConstraints: ['mobile_first'],
      softConstraints: ['avoid_dense_text_mobile'],
      a11yChecklist: ['contrast_aa', 'screen_reader_friendly', 'keyboard_navigable'],
      bestFor: ['saas', 'product', 'enterprise'],
      avoidFor: ['blog', 'portfolio'],
      estimatedSize: 'xl',
      hasAnimations: false,
      requiresJs: false,
    },
  },
  'faq-accordion': {
    component: FAQAccordion as any,
    meta: {
      kind: 'faq',
      variant: 'accordion',
      name: 'FAQ • Accordion',
      description: 'Expandable accordion-style FAQ section.',
      contentSlots: [
        { key: 'headline', type: 'text', required: true, maxLength: 100 },
        { key: 'subheadline', type: 'text', required: false, maxLength: 200 },
        { key: 'faqs', type: 'faq[]', required: true },
      ],
      hardConstraints: ['mobile_first'],
      softConstraints: ['limit_animations'],
      a11yChecklist: ['contrast_aa', 'keyboard_navigable'],
      bestFor: ['product', 'service', 'support'],
      avoidFor: ['portfolio', 'blog'],
      estimatedSize: 'md',
      hasAnimations: true,
      requiresJs: true,
    },
  },
  'faq-grid': {
    component: FAQGrid as any,
    meta: {
      kind: 'faq',
      variant: 'grid',
      name: 'FAQ • Grid Layout',
      description: 'FAQ items displayed in a responsive grid.',
      contentSlots: [
        { key: 'headline', type: 'text', required: true, maxLength: 100 },
        { key: 'subheadline', type: 'text', required: false, maxLength: 200 },
        { key: 'faqs', type: 'faq[]', required: true },
      ],
      hardConstraints: ['mobile_first'],
      softConstraints: ['optimize_for_thumb_reach'],
      a11yChecklist: ['contrast_aa', 'keyboard_navigable'],
      bestFor: ['product', 'service', 'landing'],
      avoidFor: ['blog', 'documentation'],
      estimatedSize: 'md',
      hasAnimations: false,
      requiresJs: false,
    },
  },
  'contact-split-map': {
    component: ContactSplitMap as any,
    meta: {
      kind: 'contact',
      variant: 'split-map',
      name: 'Contact • Split Map',
      description: 'Contact form with map and info sidebar.',
      contentSlots: [
        { key: 'headline', type: 'text', required: true, maxLength: 100 },
        { key: 'subheadline', type: 'text', required: false, maxLength: 200 },
        { key: 'contactInfo', type: 'contactInfo', required: false },
      ],
      hardConstraints: ['mobile_first', 'form_label_required'],
      softConstraints: ['optimize_for_thumb_reach'],
      a11yChecklist: ['contrast_aa', 'keyboard_navigable', 'focus_visible'],
      bestFor: ['business', 'service', 'local'],
      avoidFor: ['blog'],
      estimatedSize: 'lg',
      hasAnimations: false,
      requiresJs: true,
    },
  },
  'contact-multi-channel': {
    component: ContactMultiChannel as any,
    meta: {
      kind: 'contact',
      variant: 'multi-channel',
      name: 'Contact • Multi Channel',
      description: 'Multiple contact options in a grid layout.',
      contentSlots: [
        { key: 'headline', type: 'text', required: true, maxLength: 100 },
        { key: 'subheadline', type: 'text', required: false, maxLength: 200 },
        { key: 'channels', type: 'channel[]', required: false },
      ],
      hardConstraints: ['mobile_first'],
      softConstraints: ['optimize_for_thumb_reach'],
      a11yChecklist: ['contrast_aa', 'keyboard_navigable'],
      bestFor: ['enterprise', 'support', 'service'],
      avoidFor: [],
      estimatedSize: 'md',
      hasAnimations: false,
      requiresJs: false,
    },
  },
  'gallery-grid': {
    component: GalleryGrid as any,
    meta: {
      kind: 'gallery',
      variant: 'grid',
      name: 'Gallery • Grid',
      description: 'Filterable grid gallery with categories.',
      contentSlots: [
        { key: 'headline', type: 'text', required: true, maxLength: 100 },
        { key: 'subheadline', type: 'text', required: false, maxLength: 200 },
        { key: 'images', type: 'images', required: true },
      ],
      hardConstraints: ['mobile_first', 'img_alt_required'],
      softConstraints: ['avoid_adjacent_heavy_imagery'],
      a11yChecklist: ['contrast_aa', 'keyboard_navigable'],
      bestFor: ['portfolio', 'creative', 'product'],
      avoidFor: [],
      estimatedSize: 'xl',
      hasAnimations: true,
      requiresJs: true,
    },
  },
  'gallery-carousel-full': {
    component: GalleryCarousel as any,
    meta: {
      kind: 'gallery',
      variant: 'carousel-full',
      name: 'Gallery • Carousel Full',
      description: 'Full-width carousel with thumbnails.',
      contentSlots: [
        { key: 'headline', type: 'text', required: true, maxLength: 100 },
        { key: 'subheadline', type: 'text', required: false, maxLength: 200 },
        { key: 'images', type: 'images', required: true },
      ],
      hardConstraints: ['mobile_first', 'img_alt_required'],
      softConstraints: ['limit_animations'],
      a11yChecklist: ['contrast_aa', 'keyboard_navigable', 'reduced_motion_safe'],
      bestFor: ['portfolio', 'showcase', 'product'],
      avoidFor: [],
      estimatedSize: 'xl',
      hasAnimations: true,
      requiresJs: true,
    },
  },
  'blog-card-grid': {
    component: BlogCardGrid as any,
    meta: {
      kind: 'blog',
      variant: 'card-grid',
      name: 'Blog • Card Grid',
      description: 'Blog posts in card grid layout.',
      contentSlots: [
        { key: 'headline', type: 'text', required: true, maxLength: 100 },
        { key: 'subheadline', type: 'text', required: false, maxLength: 200 },
        { key: 'posts', type: 'post[]', required: true },
      ],
      hardConstraints: ['mobile_first'],
      softConstraints: ['avoid_dense_text_mobile'],
      a11yChecklist: ['contrast_aa', 'keyboard_navigable'],
      bestFor: ['blog', 'news', 'magazine'],
      avoidFor: [],
      estimatedSize: 'lg',
      hasAnimations: false,
      requiresJs: false,
    },
  }
};
